[package]
name = "onebpp"
version = "0.1.0"
edition = "2021"
publish = false
authors = ["erin petra sofiya moon <erin@hecke.rs"]

[dependencies]
bootshim = { path = "../bootshim" }
tock-registers = { git = "https://github.com/tock/tock.git#59b50204194107f9e70c27470e66dea7db5f518f" }
