[package]
name = "bootshim"
version = "0.1.0"
edition = "2021"
publish = false
authors = ["erin petra sofiya moon <erin@hecke.rs"]

[dependencies]
cortex-a = "7.2"
tock-registers = "0.7"
bootshim-macros = { path = "macros" }
